site_name: Present
site_url: https://wickwood-llc.github.io/present-docs
theme:
  name: material
  features:
    - content.action.edit
    - content.action.view
    - content.code.copy
    - content.tooltips

nav:
  - index.md
  - create-presentations/index.md
  - 'Publishing': publishing.md
  - background-audio-guide/index.md

repo_url: https://github.com/Wickwood-LLC/present-docs/
edit_uri: edit/master/docs/

markdown_extensions:
  - admonition
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - abbr
  - toc:
      permalink: true

plugins:
  - glightbox

