site_name: Present
site_url: https://wickwood-llc.github.io/present-docs
theme:
  name: material
  features:
    - content.action.edit
    - content.action.view

nav:
  - index.md
  - create-presentations/index.md
  - background-audio-guide/index.md

repo_url: https://github.com/Wickwood-LLC/present-docs/
edit_uri: edit/master/docs/

markdown_extensions:
  - admonition
